spring:
  application:
    name: server
  cache:
    type: redis
  datasource:
    url: jdbc:h2:file:./data/chatdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 500
        format_sql: true
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6380
      # password: redis1234
      # \uC704 3\uC904(host, port, password)\uB85C \uC5F0\uACB0\uC774 \uC548 \uB420 \uACBD\uC6B0,
      # \uC704 3\uC904\uC744 \uC9C0\uC6B0\uACE0 \uC544\uB798 \uD55C \uC904\uC758 \uC8FC\uC11D(#)\uC744 \uD574\uC81C\uD558\uC5EC url \uBC29\uC2DD\uC744 \uC0AC\uC6A9\uD574 \uBCF4\uC138\uC694.
      # url: redis://:redis1234@localhost:6379

logging:
  level:
    com:
      socket: INFO
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE
        type:
          descriptor:
            sql:
              BasicBinder: TRACE